### ISSUE TITLE
SCIP 2.2, multiecho, and ethernet support in hokuyo_node

### ISSUE THREAD

**Issue by chadrockey** [ros-drivers/hokuyo_node#2]
Migrated from code.ros.org
https://code.ros.org/trac/ros-pkg/ticket/5368

Reported by:    fredpauling Owned by:   chadrockey
Priority:    major   Milestone: 
Component:   laser_drivers   Version:  
Keywords:    hokuyo_node SCIP2.2 hokuyo ethernet     Cc:  
Include in GanttChart:   no  Dependencies:  
Due to assign:   DD/MM/YYYY  Due to close:   DD/MM/YYYY
Description 

The hokuyo_node driver does not currently implement the SCIP 2.2 protocol available for newer Hokuyo lasers, nor does it provide an option to interface with ethernet lasers (e.g the UTM-30LX-EW). The SCIP 2.2 protocol defines additional commands and message structures for obtaining multi-echo scans from a compliant laser scanner (see attached specification document). I propose that the hokuyo_node package be enhanced to include this functionality. An existing open-source driver library (such as "urgwidget"  http://sourceforge.net/projects/urgwidget/) could provide a reference implementation to reduce development time.

Changed 12 months ago by fredpauling

attachment UTM-30LX-EW_Communication_Protocol_Specification.pdf   added
http://www.hokuyo-aut.jp/02sensor/07scanner/download/products/utm-30lx-ew/data/UTM-30LX-EW_protocol_en.pdf

Changed 11 months ago by chadrockey 

summary changed from SCIP 2.2 support in hokuyo_node to SCIP 2.2, multiecho, and ethernet support in hokuyo_node
Thanks for the information. Unfortunately, I'm not going to be able to resolve this for Fuerte.

There are a few issues to handle:

1.) Adding in ethernet support. This either means switching the wrapped library for hokuyo_node or adding in support otherwise (sockets/asio). This will just take time to determine the best route, but isn't something I can complete this month.

2.) Multiecho API. There are now quite a few lasers that support these features. I haven't seen anyone attempt to define an API for how to output N returns. The options would be: adding a new message, modifying the sensor_msgs/LaserScan message, or publishing on multiple topics. I'm most in favor of the multiple topics since changing the laserscan message would affect almost the entire community and adding a new message breaks existing API. This seems fair in that the use of multiecho scanners is usually comparing the returns at common indices. However, a message filter or other re-synchronization will be needed outside of the driver node. This will require a community review to make sure what is implemented is satisfactory. We'd also need to define best practices topic names.

For some good news, I did manage to get a UTM-30LX-EW to test on. I wrote a quick wrapper around the urgwidget library and that seems to work well. If you're interested in this, I could clean it up and post it to a Google Code project as a temporary solution until we decide what (if anything) to do to the existing Hokuyo node.

Changed 7 months ago by patoreilly 

Hello, was wondering if there was an update on the SCIP 2.2, multiecho, and/or ethernet support. I see there is an iri_hokuyo_node out there that supports ethernet, but not SCIP 2.2 it seems and it wasn't clear if they were still active on it. We just started looking at their code, but I would rather use the hokuyo_node itself. We have a UTM-30LX-EW. Also, I would be interested in the wrapper you wrote to the urgwidget library. Thanks for your work on this.

**Comment by chadrockey** [comment]
Current status is that I'm having difficulty acquiring test hardware.  I did manage to get the API approved:
http://www.ros.org/wiki/sensor_msgs/Reviews/2012-08-01_MultiEchoLaser_API_review_API_Review?highlight=%28PackageReviewCategory%29

I'm looking to delivering a library and node to help process multi-echo lasers in Hydro.  The driver will likely come after unless I get my hands on a laser very soon.

**Comment by fredpauling** [comment]
Thanks for the update chadrockey. Hokuyos are like hen's teeth in our lab too.

Interesting discussion on the API review page (I missed this one at the time). I concur with the final decision to provide a separate message type containing the echoes, whilst retaining the existing LaserScan message. The 'transport layer' style node/nodelet for republishing selected scans is a good idea and I fully support it. Our group's (multi-echo) SICK LD-MRS driver ( http://bazaar.launchpad.net/~csiro-asl/csiro-asl-ros-pkg/trunk/files/head:/sick_ldmrs/ ) publishes both LaserScan and PointCloud2 messages. The node provides a switch for publishing first/last return on the LaserScan topics and the PointCloud2 topic structure we used is similar to your proposed MultiEchoLaserScan message.

Regarding the Hokuyo driver, the URG widget is written and (actively) maintained by Hokuyo employees so I personally think the best option would be to switch libraries to reduce code maintenance overhead. Of course, some testing would be required to show that the timing accuracy and CPU load are equivalent or better than the original node.  We are very much hoping that you can get hands on a laser unit so that the updated driver can appear in Hydro.

Thanks for all your efforts on this.

**Comment by SentinalBais** [comment]
How close are you to releasing the update? 
Is it possible to disable mult-echo in order to use the current drivers?

**Comment by chadrockey** [comment]
Are you having an issue with hokuyo_node?  It should be functional on USB hokuyos.

**Comment by SentinalBais** [comment]
no I haven't tried it out yet

I was thinking of acquiring the UTM-30LX-EW (which uses Ethernet and multi-echo) just wondering how close you are to finishing the patch

If its not soon I will probably use the SICK1xx node with the SICK LMS111 (which use Ethernet also)  or consider buying a usb Hokuyo. (we are running out of usb ports, i am pretty sure you wont be able to run the hokuyo on a usb hub)

**Comment by chadrockey** [comment]
I have a unit on order.  I suspect support will be added in Hydromedusa - 2 months or so from now.

**Comment by chadrockey** [comment]
This work is now completed in urg_node.

https://github.com/ros-drivers/urg_node

**Comment by fredpauling** [comment]
This is great work Chad, thanks for putting in the hard yards! I'm sure it will be worth the effort. We'll be putting this to work shortly. Many thanks.
