### ISSUE TITLE
locale::facet::_S_create_c_locale name not valid

### ISSUE THREAD

**Issue by t1jump** [ros-drivers/hokuyo_node#3]
I'm trying to get the Hokuyo_node running on an ARM based BeagleBone runnung Ubuntu Quantal and ROS Groovy. I installed laser_drivers from source(see below).

When I run $ roslaunch hokuyo_node hokuyo_test.launch I get the following error:

core service [/rosout] found
process[hokuyo-1]: started with pid [1139]
terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid
[hokuyo-1] process has died [pid 1139, exit code -6, cmd /home/rkrs/ros_ws/laser_drivers/hokuyo_node/bin/hokuyo_node __name:=hokuyo __log:=/home/rkrs/.ros/log/aa4e49d8-c248-11e2-bdff-bc6a299c667c/hokuyo-1.log].
log file: /home/rkrs/.ros/log/aa4e49d8-c248-11e2-bdff-bc6a299c667c/hokuyo-1*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete
done
Unhandled exception in thread started by 
sys.excepthook is missing
lost sys.stderr

Research on the 'std::runtime_error'  what():  locale::facet::_S_create_c_locale name not valid brought me to three sites, but I'm unsure of what is what.

http://stackoverflow.com/questions/1922713/valid-locale-names
https://svn.boost.org/trac/boost/ticket/4688
http://www.gnu.org/software/libiconv/

I don't know if this is an issue with the hokuyo_node, with boost, other??? so I'm reporting the issue here.

laser_driver install process
cd ~/ros_ws
wstool set laser_drivers https://code.ros.org/svn/ros-pkg/stacks/laser_drivers/trunk --svn -y
rosws update laser_drivers
source ~/ros_ws/setup.bash

echo $ROS_PACKAGE_PATH
/home/rkrs/ros_ws/laser_drivers:/home/rkrs/ros_ws/imu_um6:/home/rkrs/ros_ws/executive_smach:/home/rkrs/ros_ws/filters:/home/rkrs/ros_ws/xacro:/home/rkrs/ros_catkin_ws/install_isolated/share:/home/rkrs/ros_catkin_ws/install_isolated/stacks

rosmake laser_drivers

**Comment by chadrockey** [comment]
Looks like this is an issue with boost::filesystem.  Have you tried the configuration fix when running that was mentioned in this thread:
https://svn.boost.org/trac/boost/ticket/4688

"LC_ALL=C in our launcher"

Otherwise, I would give urg_node a shot to see if it works instead:
https://github.com/ros-drivers/urg_node

Let me know if you resolve this and I would accept a pull request to fix this for arm users.  Otherwise, this driver is intended for PR2 and LTS support and I'm not actively developing it for arm.

**Comment by t1jump** [comment]
Just to confirm, LC=ALL is already set to =C in the hokuyo_node launcher?

**Comment by chadrockey** [comment]
I think that is dependent on your machine.  I think you should try to run something like:
$ LC_ALL=C  ./hokuyo_node

(Do this in your devel/lib/hokuyo_node folder).

**Comment by t1jump** [comment]
I called $ locale and got:

rkrs@bbone2:~$ locale
LANG=
LANGUAGE=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
rkrs@bbone2:~$ 

Looks like LC_ALL needs to be changed to LC_ALL=C. Any tips on how to do this?

**Comment by chadrockey** [comment]
Try 'export LC_ALL=C'

or just set it for a command like I said above.

If it works consistently you can set the export command in your .bashrc

**Comment by t1jump** [comment]
Running 'export LC_ALL=C' cleared the error. My next step is to set this in the .bashrc. It appears that with minimal installs on devices like the BeagleBone, 'locale' has no settings.

This issue may be a good add to the Troubleshooting section on the hokuyo_node tutorial.

**Comment by chadrockey** [comment]
Great!  Glad to hear it.

Feel free to add that to troubleshooting if you think it will help other users.
