### ISSUE TITLE
comminication failure with hokuyo_node on ARM (BeagleBone) and Groovy

### ISSUE THREAD

**Issue by t1jump** [ros-drivers/hokuyo_node#4]
I've been trying to connect the URG-04x Hokuyo to a USB port on a BeagleBone. The sensor works fine on a PC running ROS Fuerte and hokuyo_node but at any point trying to connect to the sensor through the BeagleBone and ROS Groovy throws the error:

```
[ERROR] [1369266308.601881517]: Exception thrown while opening Hokuyo.
timeout reached (in hokuyo::laser::laserReadline)
```

I've done every check I can figure out to run on the USB port on the Beagle and all pass. The USB port on the Beagle works will other apps/sensors so at this point I'm guessing the issue is with the driver in the hokuyo_node.

I am wondering if I have the Groovy version of laser_drivers. Sudo apt-get install ros-groovy-laser-drivers fails (cannot find package) so I installed from source. If there is a way to confirm which version I have installed please advise.

**Comment by chadrockey** [comment]
Please check permissions on the serial port /dev/ttyACM.... And make sure you have the right one.

Also report if you can open a console and send commands to the laser with mini com, etc:
http://www.hokuyo-aut.jp/02sensor/07scanner/download/urg_programs_en/scip_commands_page.html

**Comment by t1jump** [comment]
To verify, if by check permissions you are referring to $ ls -l /dev/ttyACM0, yes I can do this. I also installed minicom and can run "VV", "PP", etc. I did not try any of the features that would alter the setting of the operation mode of the Hokuyo.

**Comment by t1jump** [comment]
I decided to try the Hokuyo through a serial to USB converter to see if the error had something to do with ttyACM0 but I get the same error as reported above. As mentioned above, every connection to the Hokuyo through picocom, minicom and through the Fuerte install on the laptop succeeds and it is only the connection and running of the hokuyo_node on the Beagle that has any issues.

**Comment by chadrockey** [comment]
https://github.com/ros-drivers/urg_node

Does the issue happen with URG node?  I suspect there's something odd with your environment that boost doesn't like related to hokuyo_node.  See https://github.com/ros-drivers/hokuyo_node/issues/3

**Comment by t1jump** [comment]
I have built the urg_node (wstool set and rosmake). How do I launch it?

**Comment by chadrockey** [comment]
urg_node should be catkin and cmake.  Please look through the catkin tutorials:

http://ros.org/wiki/catkin/Tutorials

**Comment by t1jump** [comment]
Is laser_drivers catkin?

**Comment by chadrockey** [comment]
As of the hydro-devel branch, yes, hokuyo_node, sicktoolbox, and sicktoolbox_wrapper are all catkin.

**Comment by t1jump** [comment]
On the ROS hokuyo_node wiki there are three release options (Electric, Fuerte, Groovy). All three list the same source for the drivers (svn https://code.ros.org/svn/ros-pkg/stacks/laser_drivers/trunk). As I'm running Groovy on the Beagle, is this the correct source and does it go in a ros_ws, or should I be getting the laser_drivers from a different source?

**Comment by chadrockey** [comment]
https://github.com/ros-drivers/hokuyo_node/branches lists all current and past branches from electric onwards.  The hydro-devel branch should compile on groovy.

**Comment by t1jump** [comment]
Installed the latest version of hokuyo_node but I get the same error. At least now, when I run getID it replies "ttyACM? is quiet". So??? Again, the same hokuyo works on a Fuerte install. Is there supposed to be a code to start the hokuyo broadcasting.

Also, I tried to install urg_node but the rosdep ros-groovy-urg-c failed. This binary must not install on an ARM so I would need to get this rosdep from source.

Does the urg-node need to be working to allow the hokuyo_node to operate correctly?

**Comment by t1jump** [comment]
Got all the dependencies for urg_node installed from source. urg_node makes a successful connection to the Hokuyo URG-04X!! Also does not seem to need any of the previous settings (rosparam 117, chmod of /dev/ttyACM0, etc.), just run a roscore, then rosrun urg_node urg_node.

On the urg_node github page it points to the urg_node as a replacement for the hokuyo_node. Please verify that if the urg_node is functional the hokuyo_node can be abandoned.

**Comment by chadrockey** [comment]
This node works with more hokuyos than hokuyo_node, but its not currently a
direct replacement.  I do recommend it for new users and new robots.

Hokuyo_node will be supported until this node is mature and until PR2 can
switch over.

This is also not a great place to ask this question.  Please see the
support guidelines:
http://www.ros.org/wiki/Support

**Comment by chadrockey** [comment]
Closing for now.  ARM is not a targeted platform for Hokuyo Node.  Please try urg_node first if you are using arm.

If you feel that you need hokuyo_node for arm, and have a fix, please send a pull request.

**Comment by t1jump** [comment]
Hi Chad,

Using urg_node for ARM works very well. I see no need to pursue Hokuyo_node for the ARM.

Cheers,

T. Jump
