### ISSUE TITLE
Missing log4cxx headers when building against latest ros_comm.

### ISSUE THREAD

**Issue by trainman419** [ros-drivers/hokuyo_node#7]
When building against the latest development version of ros_comm, which attempts to remove the dependency on log4cxx, hokuyo_node fails to build with the following error:

```
[ 40%] Building CXX object CMakeFiles/getFirmwareVersion.dir/src/getFirmwareVersion.cpp.o
/usr/lib/ccache/c++   -DROS_PACKAGE_NAME=\"hokuyo_node\" -I/tmp/buildd/ros-hydro-hokuyo-node-1.7.7-0raring-20140106-2312/obj-arm-linux-gnueabihf/devel/include -I/tmp/buildd/ros-hydro-hokuyo-node-1.7.7-0raring-20140106-2312/include -I/opt/ros/hydro/include    -o CMakeFiles/getFirmwareVersion.dir/src/getFirmwareVersion.cpp.o -c /tmp/buildd/ros-hydro-hokuyo-node-1.7.7-0raring-20140106-2312/src/getFirmwareVersion.cpp
/tmp/buildd/ros-hydro-hokuyo-node-1.7.7-0raring-20140106-2312/src/getFirmwareVersion.cpp: In function 'int main(int, char**)':
/tmp/buildd/ros-hydro-hokuyo-node-1.7.7-0raring-20140106-2312/src/getFirmwareVersion.cpp:56:5: error: 'log4cxx' has not been declared
/tmp/buildd/ros-hydro-hokuyo-node-1.7.7-0raring-20140106-2312/src/getFirmwareVersion.cpp:56:24: error: expected ';' before 'my_logger'
/tmp/buildd/ros-hydro-hokuyo-node-1.7.7-0raring-20140106-2312/src/getFirmwareVersion.cpp:57:5: error: 'my_logger' was not declared in this scope
/tmp/buildd/ros-hydro-hokuyo-node-1.7.7-0raring-20140106-2312/src/getFirmwareVersion.cpp:57:25: error: 'g_level_lookup' is not a member of 'ros::console'
make[4]: *** [CMakeFiles/getFirmwareVersion.dir/src/getFirmwareVersion.cpp.o] Error 1
```

I believe the fix for this should be as simple as adding an explicit dependency on log4cxx, but it might be more involved if hokuyo_node is relying on the underlying implementation of ros logging being log4cxx.

**Comment by chadrockey** [comment]
I would rather remove the dependency on log4cxx.  I think it's only used to disable console output in 'quiet mode' scripts:

https://github.com/ros-drivers/hokuyo_node/blob/hydro-devel/src/getFirmwareVersion.cpp#L56

**Comment by trainman419** [comment]
Agreed. It looks like the only other place that it's used is in getID:

https://github.com/ros-drivers/hokuyo_node/blob/hydro-devel/src/getID.cpp#L56

I know the PR2 uses the hokuyo get ID utility in the udev rules to create device-specific symlinks, so we should make sure we find the equivalent ROS API to disable logging output, if it's even still necessary.

**Comment by trainman419** [comment]
I've asked for a general recommendation about this on ROS answers: http://answers.ros.org/question/116436/missing-log4cxx-on-latest-ros_comm/

**Comment by dirk-thomas** [comment]
Same rational as PR2/pr2_ethercat_drivers#62.

**Comment by dirk-thomas** [comment]
Please address the missing explicit dependency on log4cxx to unbreak the build on the farm.
